import type { GalleryPair } from '@/types'

export const beforeAfterPairs: GalleryPair[] = [
  {
    before: { src: '/img/before-and-after/blonde-before-hair.jpg', alt: 'mid blonde hair in need of styling' },
    after: { src: '/img/before-and-after/blonde-after-hair.jpg', alt: 'mid blonde hair styled and curled' },
    title: 'Volume & Movement',
    description: 'From flat to fabulous — bouncy curls with body that lasts.',
    category: 'Blow Dry',
  },
  {
    before: { src: '/img/before-and-after/blonde-bob-before.jpg', alt: 'short blonde hair with dark roots' },
    after: { src: '/img/before-and-after/short-blonde-after.jpg', alt: 'short bobbed blonde hair freshly colored and styled' },
    title: 'Root Refresh',
    description: 'Roots blended, ends brightened — a full-colour bob transformation.',
    category: 'Colour',
  },
  {
    before: { src: '/img/before-and-after/bronde-hair-before.jpg', alt: 'mid length bronde straight hair needing a cut' },
    after: { src: '/img/before-and-after/bronde-hair-after.jpg', alt: 'mid length straight bronde hair freshly coloured and styled' },
    title: 'Bronde Glow',
    description: 'Warm bronde tones, a fresh cut, and a gloss-smooth finish.',
    category: 'Colour & Cut',
  },
  {
    before: { src: '/img/extra-images/long-dark-before.jpg', alt: 'long dark wavy hair' },
    after: { src: '/img/extra-images/dark-bob-styled.jpg', alt: 'short dark bobbed hair styled' },
    title: 'The Big Chop',
    description: 'Trading length for shape — a bold, chic bob that changed everything.',
    category: 'Cut & Style',
  },
  {
    before: { src: '/img/before-and-after/extra-long-brown-before.jpg', alt: 'very long frizzy hair' },
    after: { src: '/img/before-and-after/extra-long-brown-after.jpg', alt: 'very long curled hair' },
    title: 'Curl Revival',
    description: 'Frizz tamed, curls defined — long hair transformed from wild to wow.',
    category: 'Blow Dry',
  },
  {
    before: { src: '/img/before-and-after/sleek-bob-before.jpg', alt: 'long frizzy blonde hair' },
    after: { src: '/img/before-and-after/sleek-bob-after.jpg', alt: 'sleek bob' },
    title: 'The Sleek Bob',
    description: 'From frizzy and long to a razor-sharp, sleek bob — pure confidence.',
    category: 'Cut & Style',
  },
  {
    before: { src: '/img/before-and-after/blonde-wavy-before.jpg', alt: 'wet hair about to be cut' },
    after: { src: '/img/before-and-after/blonder-wavy-after-2.jpg', alt: 'blonde hair curled and styled' },
    title: 'Blonde Waves',
    description: 'Fresh colour and sculpted waves for a sun-kissed, effortless finish.',
    category: 'Colour & Style',
  },
  {
    before: { src: '/img/before-and-after/before-long-hightlights.jpg', alt: 'long hair before highlights' },
    after: { src: '/img/before-and-after/after-long-highlights.jpg', alt: 'long hair with fresh highlights' },
    title: 'Highlights & Lift',
    description: 'Sun-kissed highlights woven through for a bright, multi-dimensional finish.',
    category: 'Highlights',
  },
  {
    before: { src: '/img/before-and-after/before-long-highlights-2.jpg', alt: 'long hair before highlights treatment' },
    after: { src: '/img/before-and-after/after-long-highlights-2.jpg', alt: 'long hair with blended highlights' },
    title: 'Illuminating Highlights',
    description: 'Soft, blended highlights woven through for a natural, radiant result.',
    category: 'Highlights',
  },
  {
    before: { src: '/img/before-and-after/white-bob-before.jpg', alt: 'bob before colour treatment' },
    after: { src: '/img/before-and-after/white-bob-after.jpg', alt: 'white blonde bob after colour' },
    title: 'White Bob',
    description: 'A bold colour lift to a crisp, bright white-blonde bob.',
    category: 'Colour & Cut',
  },
  {
    before: { src: '/img/before-and-after/short-blonde-before.jpg', alt: 'short blonde hair before' },
    after: { src: '/img/before-and-after/blonde-bob-after.jpg', alt: 'blonde bob after colour and cut' },
    title: 'Blonde Bob Refresh',
    description: 'Roots lifted and shape refined for a polished, fresh blonde bob.',
    category: 'Colour & Cut',
  },
]

export const freshestHairImages = [
  { src: '/img/extra-images/extra-long-brown-after-side.jpg', alt: 'long brown hair from side view' },
  { src: '/img/extra-images/blonde_bridal_up.jpg', alt: 'bridal hair style up with pearls' },
  { src: '/img/extra-images/blond_bod_side.jpg', alt: 'short blonde hair side view' },
  { src: '/img/extra-images/blonde_bob_back.jpg', alt: 'short blonde hair back view' },
  { src: '/img/extra-images/bridal-hair-up-spiral-curls.jpg', alt: 'bridal hair style with blonde ringlet curls' },
  { src: '/img/extra-images/bronde-bob-side.jpg', alt: 'side view of bronde bobbed hair' },
  { src: '/img/extra-images/bronde-bob.jpg', alt: 'bronde bobbed hair' },
  { src: '/img/extra-images/dark-bob-back.jpg', alt: 'dark bobbed hair from back' },
  { src: '/img/extra-images/dark-bob.jpg', alt: 'dark bobbed hair' },
  { src: '/img/extra-images/brunette-curls.jpg', alt: 'long brunette curly hair' },
  { src: '/img/extra-images/long-blonde-back.jpg', alt: 'long blonde hair from the back' },
  { src: '/img/extra-images/long-blonde.jpg', alt: 'long blonde hair' },
  { src: '/img/extra-images/red-bob.jpg', alt: 'short red bob' },
  { src: '/img/extra-images/red-bob-back.jpg', alt: 'short red bobbed hair from the back view' },
  { src: '/img/hair/lorraine-hair-side.jpg', alt: 'hair styled by Paula Lorraine' },
  { src: '/img/extra-images/short-dark-blonde.jpg', alt: 'short dark blonde hair' },
  { src: '/img/extra-images/blonde-layers.jpg', alt: 'blonde hair with layered cut' },
  { src: '/img/extra-images/blonde-wavy-after-one.jpg', alt: 'blonde wavy hair styled' },
  { src: '/img/extra-images/bridal-hair.jpg', alt: 'bridal hair updo' },
  { src: '/img/extra-images/bridal.jpg', alt: 'elegant bridal hairstyle' },
  { src: '/img/extra-images/long-ash-highlights.jpg', alt: 'long hair with ash highlights' },
  { src: '/img/extra-images/long-highlights.jpg', alt: 'long hair with highlights' },
  { src: '/img/extra-images/midlength-highlights-back.jpg', alt: 'mid-length highlighted hair back view' },
  { src: '/img/extra-images/midlength-highlights.jpg', alt: 'mid-length hair with highlights' },
  { src: '/img/extra-images/prom-hair-ringlets-french-braid.jpg', alt: 'prom hair with ringlets and french braid' },
  { src: '/img/extra-images/prom-hair.jpg', alt: 'prom hair updo' },
  { src: '/img/extra-images/wedding-hair-up-spiral.jpg', alt: 'wedding hair updo with spiral curls' },
  { src: '/img/extra-images/white-bob.jpg', alt: 'white blonde bob haircut' },
  { src: '/img/hair/bridal-sample-1.jpg', alt: 'bridal hair sample' },
  { src: '/img/hair/brunette-curly-hair.jpg', alt: 'brunette curly hair' },
  { src: '/img/hair/sample-red-bob.jpg', alt: 'red bob haircut' },
  { src: '/img/hair/short-white-hair.jpg', alt: 'short white blonde hair' },
]
